PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
prefix pmofn: <http://premon.fbk.eu/ontology/fn#>
PREFIX fn15schema: <https://w3id.org/framester/framenet/tbox/>
PREFIX frame: <https://w3id.org/framester/framenet/abox/frame/>
PREFIX fe: <https://w3id.org/framester/framenet/abox/fe/>
PREFIX lu: <https://w3id.org/framester/framenet/abox/lu/>

CONSTRUCT {
    ?f a <https://w3id.org/framester/framenet/tbox/Frame> .
    ?f owl:sameAs ?s .
	
	?f a fn15schema:Frame .
	?f a owl:Class .
} WHERE {
		?s a pmofn:Frame .
		?s rdfs:label ?label .
    	BIND (IRI(CONCAT("https://w3id.org/framester/framenet/abox/frame/",STR(?label))) AS ?f)
	
} 
